# Generated by Django 4.2.5 on 2023-09-14 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newspost',
            old_name='newstitle',
            new_name='title',
        ),
    ]
